#!/usr/bin/env bash

#COMPOSER_MEMORY_LIMIT=-1 composer create-project --repository=https://repo.magento.com/ magento/project-community-edition .
su www-data <<EOSU
/var/www/html/bin/magento setup:install --base-url="$MAGENTO_URL" --backend-frontname="$MAGENTO_BACKEND_FRONTNAME" --language=$MAGENTO_LANGUAGE --timezone=$MAGENTO_TIMEZONE --currency=$MAGENTO_DEFAULT_CURRENCY --db-host="$MYSQL_HOST" --db-name="$MYSQL_DATABASE" --db-user="$MYSQL_USER" --db-password="$MYSQL_PASSWORD" --use-secure=$MAGENTO_USE_SECURE --base-url-secure="$MAGENTO_BASE_URL_SECURE" --use-secure-admin=$MAGENTO_USE_SECURE_ADMIN --admin-firstname="$MAGENTO_ADMIN_FIRSTNAME" --admin-lastname="$MAGENTO_ADMIN_LASTNAME" --admin-email="$MAGENTO_ADMIN_EMAIL" --admin-user="$MAGENTO_ADMIN_USERNAME" --admin-password="$MAGENTO_ADMIN_PASSWORD" --elasticsearch-host="$MAGENTO_ELASTICSEARCH_HOST" --elasticsearch-port="$MAGENTO_ELASTICSEARCH_PORT" --search-engine="$MAGENTO_SEARCH_ENGINE" --cleanup-database \
&& /var/www/html/bin/magento module:disable Magento_TwoFactorAuth \
&& /var/www/html/bin/magento cache:flush
EOSU

#\ && /var/www/html/bin/magento deploy:mode:set developer